### ISSUE TITLE
to_pickle()

### ISSUE THREAD

**Issue by eberhardgade** [multimodal-europarl/pymmep#9]
Within eaf_container.py
Regarding attribute: Eaf_Container.to_pickle()

This should obviously accept a path as argument as not everybody wants to save in ./output

**Comment by BobBorges** [comment]
suggestion: set default output directory to `_output/` so git will ignore it (leading underscore). we don't want to (accidentally)  version control pickle files.

**Comment by eberhardgade** [comment]
6c70da98ff56cd28cb05f679ef5638d76ea2d3bc solved this.
